Refactored package
persian-tools/dart-persian-tools pull request #17
Opened 2021-06-03 21:38 UTC by makhosravi

The core feature dart file has the name of the feature.
All model classes are in the ```model.dart``` file.
Constants moved to the ```lib/src/constants/feature_name/constants.dart``` file.
Values that are not used as public APIs were converted to private access.

2021-06-07 15:28 UTC, payam-zahedi requested changes
Excellent work @makhosravi. 
Before merging this partnership, you should consider the following tasks.

- run `dart test .`  command
- run dart format command
- Make sure commit messages are up to 70 characters long.
- make sure that you updated the README.md file

2021-06-07 15:28 UTC, payam-zahedi commented on lib/src/core/bill/bill.dart
> +    return billTypesMap[billTypeKey] ?? unknown;
Are you sure that you run the `dart format` command?

2021-06-07 15:28 UTC, payam-zahedi commented on lib/src/core/vehicle_plate/vehicle_plate.dart
> +}
Why should we have an abstract class here? We can turn its methods into the high-order private methods.

2021-06-07 15:29 UTC, payam-zahedi commented
@EhsanAramide I think you should also review this PR.

2021-06-07 16:04 UTC, EhsanAramide reviewed
Well done.
I am very interested about your contribution but before merging first of all check the testcases in `test` directory then check the `example` directory and ensure everything works fine.
Also take code coverage after refactoring it shouldn't be under 95 percent. (Instructions are available in `.github/workflows/test.yml` directory )

2021-06-07 22:00 UTC, ali-master commented
Well done boys, you are all heroes. Thanks for helping the PersianTools family to grow faster.

2021-06-12 04:40 UTC, payam-zahedi approved these changes
Well done Khosro, everything looks great.

2021-06-12 04:41 UTC, payam-zahedi commented
@EhsanAramide can you check the changes too? I don't see any problem

2021-06-12 05:26 UTC, EhsanAramide reviewed
Well done, everything was fine.

2021-06-12 06:11 UTC, merged