Update/NumberToWords
persian-tools/dart-persian-tools pull request #29
Opened 2021-08-30 03:51 UTC by makhosravi

- Updated NumberToWords algorithm
- Added test cases
- Removed method and extension for ``` String``` type numbers to focus the feature on safe ``` integer``` values, removed related examples and test cases
- Added doc for methods and updated README.md

2021-08-30 04:38 UTC, payam-zahedi commented
@EhsanAramide Why we have broken codecov task here?

2021-08-30 17:40 UTC, payam-zahedi requested changes
Well done @m-khooryani, I enjoyed spending time reviewing this clean code. 
Check comments and apply your changes.

2021-08-30 17:40 UTC, payam-zahedi commented on lib/src/core/number_to_words/number_to_words.dart
> +  } else if (number >= 11 && number <= 19) return _getWord(number);
I think we can make these three lines more efficient and readable.  Something like:

``` dart
if ( number <=19 && number!=10 ) return _getWord(number);
```

2021-08-30 17:40 UTC, payam-zahedi commented on lib/src/core/number_to_words/number_to_words.dart
> +  } else if (number >= 11 && number <= 19) return _getWord(number);
Also, you can write comment to make it more understandable.

2021-08-30 17:40 UTC, payam-zahedi commented on lib/src/core/number_to_words/number_to_words.dart
> +  if (number == 0) return '';
I like the way this algorithm works.

2021-08-30 17:40 UTC, payam-zahedi commented on lib/src/core/number_to_words/number_to_words.dart
>    if (number == 0) return zeroFa;
You have checked this condition in multiple functions. I think you can only check it in `_perform` function.

2021-08-30 17:40 UTC, payam-zahedi commented on lib/src/core/number_to_words/number_to_words.dart
> +String? numberToWords(int number, {bool ordinal = false}) {
Is it possible for this method to return a null value? If not, we can make this null safe, and it would be a great improvement.

2021-08-30 17:41 UTC, EhsanAramide commented
> @EhsanAramide Why we have broken codecov task here?

do you think does it have any relation with a deletion on `lib/src/internal_methods.dart`?

2021-08-31 04:42 UTC, payam-zahedi commented
> do you think does it have any relation with a deletion on `lib/src/internal_methods.dart`?

I have no idea! The internal_method.dart file doesn't change in this PR.

2021-09-14 06:17 UTC, payam-zahedi approved these changes
Great work @makhosravi, You did everything good. We will try to fix the issue that we have in our CI/CD workflow. After that, we will merge this PR.

2021-09-14 16:08 UTC, EhsanAramide commented
We decided to close the pull request for some errors which occur in calculating delta test coverage, because of conflicts in compared heads' SHA.
Open another pull request again and for next time don't force-push the commit history.
Thanks for your contributions :octocat:.

2021-09-14 16:08 UTC, closed without merging